# Generated by Django 5.0.2 on 2024-03-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0002_delete_usertable"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="Designation",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="profile_image_table",
            name="video_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
