# Generated by Django 5.0.2 on 2024-03-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0004_alter_profile_image_table_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile_image_table",
            name="video_link",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
