# Generated by Django 5.0.2 on 2024-04-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0006_alter_profile_image_table_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course_table",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("weeks", models.CharField(blank=True, default=None, max_length=20)),
                ("text", models.JSONField(blank=True, default=list, null=True)),
                ("heading", models.CharField(default=list, max_length=255)),
                ("video", models.CharField(blank=True, max_length=128)),
                ("PPT", models.CharField(blank=True, max_length=128)),
                ("course_name", models.CharField(blank=True, max_length=255)),
                ("course_id", models.CharField(blank=True, max_length=20)),
                ("headings", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="profile_image_table",
            name="ppts",
            field=models.FileField(blank=True, null=True, upload_to="pdf/"),
        ),
    ]
