# Generated by Django 5.0.2 on 2024-04-02 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0007_course_table_profile_image_table_ppts"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_table",
            name="date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="course_table",
            name="time",
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
