# Generated by Django 5.0.2 on 2024-04-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0008_course_table_date_course_table_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_table",
            name="course_id",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
