# Generated by Django 5.0.2 on 2024-04-03 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0010_alter_course_table_course_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseTable1",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("weeks", models.CharField(blank=True, default=None, max_length=20)),
                ("text", models.JSONField(blank=True, default=list, null=True)),
                ("heading", models.CharField(default=list, max_length=255)),
                ("video", models.CharField(blank=True, max_length=128)),
                ("PPT", models.CharField(blank=True, max_length=128)),
                ("course_name", models.CharField(blank=True, max_length=255)),
                ("course_id", models.CharField(blank=True, max_length=20)),
                ("headings", models.CharField(blank=True, max_length=255)),
                (
                    "date",
                    models.DateField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "time",
                    models.TimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
