# Generated by Django 5.0.2 on 2024-04-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0012_rename_id_coursetable1_courseid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_table",
            name="course_id",
            field=models.IntegerField(),
        ),
    ]
