# Generated by Django 5.0.2 on 2024-04-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0017_alter_course_table_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_table",
            name="course_id",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
