# Generated by Django 5.0.2 on 2024-04-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0025_alter_coursetable1_course_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_table",
            name="course_id",
            field=models.IntegerField(default=0),
        ),
    ]
