# Generated by Django 5.0.2 on 2024-04-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0028_course_table_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_table",
            name="level",
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
    ]
