# Generated by Django 5.0.2 on 2024-04-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0029_alter_course_table_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course_table",
            name="level",
        ),
        migrations.AddField(
            model_name="customuser",
            name="level",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
