# Generated by Django 5.0.2 on 2024-04-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0030_remove_course_table_level_customuser_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_table",
            name="PPT",
            field=models.FileField(blank=True, null=True, upload_to="pdf/"),
        ),
        migrations.AlterField(
            model_name="course_table",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
