# Generated by Django 5.0.2 on 2024-04-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0031_alter_course_table_ppt_alter_course_table_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_table",
            name="weeks",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
