# Generated by Django 5.0.2 on 2024-04-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0032_alter_course_table_weeks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_table",
            name="course_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
