# Generated by Django 5.0.2 on 2024-04-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0033_alter_course_table_course_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
    ]
