# Generated by Django 5.0.2 on 2024-04-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0035_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="videoTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=256, null=True)),
                ("video", models.FileField(blank=True, null=True, upload_to="videos/")),
            ],
        ),
    ]
