# Generated by Django 5.0.2 on 2024-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0036_videotable"),
    ]

    operations = [
        migrations.CreateModel(
            name="addThoughts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thought", models.TextField(max_length=256)),
            ],
        ),
    ]
