# Generated by Django 5.0.2 on 2024-04-19 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0037_addthoughts"),
    ]

    operations = [
        migrations.AddField(
            model_name="addthoughts",
            name="date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="videotable",
            name="date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
