# Generated by Django 5.0.2 on 2024-04-19 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0038_addthoughts_date_videotable_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="addthoughts",
            name="time",
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="videotable",
            name="time",
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
