# Generated by Django 5.0.2 on 2024-04-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0041_alter_allprogramtable_ppt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allprogramtable",
            name="PPT1",
            field=models.FileField(blank=True, null=True, upload_to="pdf/"),
        ),
        migrations.AddField(
            model_name="allprogramtable",
            name="PPT2",
            field=models.FileField(blank=True, null=True, upload_to="pdf/"),
        ),
        migrations.AddField(
            model_name="allprogramtable",
            name="PPT3",
            field=models.FileField(blank=True, null=True, upload_to="pdf/"),
        ),
        migrations.AddField(
            model_name="allprogramtable",
            name="PPT4",
            field=models.FileField(blank=True, null=True, upload_to="pdf/"),
        ),
        migrations.AddField(
            model_name="allprogramtable",
            name="PPT5",
            field=models.FileField(blank=True, null=True, upload_to="pdf/"),
        ),
        migrations.AddField(
            model_name="allprogramtable",
            name="video1",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="allprogramtable",
            name="video2",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="allprogramtable",
            name="video3",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="allprogramtable",
            name="video4",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="allprogramtable",
            name="video5",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
