# Generated by Django 5.0.2 on 2024-04-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0042_allprogramtable_ppt1_allprogramtable_ppt2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allprogramtable",
            name="PPT",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="allprogramtable",
            name="video",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
