# Generated by Django 5.0.2 on 2024-04-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0044_remove_allprogramtable_ppt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="Course_id",
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="Course_name",
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="No_of_Course",
            field=models.CharField(default="", max_length=255),
        ),
    ]
