# Generated by Django 5.0.2 on 2024-04-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0045_customuser_course_id_customuser_course_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_table",
            name="course_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
