# Generated by Django 5.0.2 on 2024-04-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0046_alter_course_table_course_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_table",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
