# Generated by Django 5.0.2 on 2024-04-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0047_course_table_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_table",
            name="active",
            field=models.BooleanField(),
        ),
    ]
