# Generated by Django 5.0.2 on 2024-04-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0048_alter_course_table_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_table",
            name="archive",
            field=models.BooleanField(default=False),
        ),
    ]
