# Generated by Django 5.0.2 on 2024-04-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0049_course_table_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_table",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
