# Generated by Django 5.0.2 on 2024-05-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0050_alter_course_table_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_table",
            name="headings1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="course_table",
            name="headings2",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
